#!/usr/bin/env bash

set -e
stack exec ghc -- -e ":q" --interactive catamorphism.hs
stack exec ghc -- -e ":q" --interactive factorial.hs
stack exec ghc -- -e ":q" --interactive fext.hs
stack exec ghc -- -e ":q" --interactive final.hs
stack exec ghc -- -e ":q" --interactive initial.hs
stack exec ghc -- -e ":q" --interactive initial_interpreter.hs
stack exec ghc -- -e ":q" --interactive recursion_schemes.hs
