#!/usr/bin/env bash

set -e
stack build
stack exec ghc -- -e ":q" --interactive categories.hs
stack exec ghc -- -e ":q" --interactive dual.hs
stack exec ghc -- -e ":q" --interactive functors.hs
stack exec ghc -- -e ":q" --interactive iso.hs
stack exec ghc -- -e ":q" --interactive kleisli.hs
stack exec ghc -- -e ":q" --interactive monoidal.hs
stack exec ghc -- -e ":q" --interactive natural.hs
